run:
  timeout: 20m
  issue-exit-code: 0 # we will change this later
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude:
    - "parameter 'args' seems to be unused, consider removing or renaming it as _"
    - "parameter 'cmd' seems to be unused, consider removing or renaming it as _"

output:
  print-linter-name: true
  sort-results: true
  uniq-by-line: false
  print-issued-lines: true

linters:
  disable-all: true
  fast: false
  enable:
    # A stricter replacement for gofmt.
    - gofumpt
    # Inspects source code for security problems.
    - gosec
    # Check for correctness of programs.
    - govet
    # Drop-in replacement of golint.
    - revive
